In [5]:
def fact(n) : 
    if n <= 0 : 
        return 1

    else : 
        return n * fact(n-1)

# insertion sort 
def isort(arr) : 
    if arr == [] : 
        return arr 
    
    else : 
        return insert(isort(arr[:-1]), arr[-1])

#### Memoization

In [10]:
fibTable = {}

def fib(n) : 
    if n in fibTable.keys() : 
        return fibTable[n]
    
    if n <= 1 : 
        value = n 
    else : 
        value = fib(n-1) + fib(n-2)

    fibTable[n] = value 
    return value 

fib(6)

8

In [11]:

#simple recursive
def fibrec(n):
    if n <= 1:
        return n 
    return fibrec(n - 1) + fibrec(n - 2)

# memoization topdown
memo ={}
def fibmem(n):
    if n <= 1:
        memo[n] = n
    if n not in memo:
        memo[n] = fibmem(n-1) + fibmem(n-2)
    return memo[n]

# DP tabulation bottom up
def fibtab(n):
    T = [0] * (n + 1)
    T[1] = 1
    for i in range(2, n + 1):
        T[i] = T[i - 1] + T[i - 2]
    return T[n]


n=int(input())
import time
t1 = time.perf_counter()
res1 = fibrec(n)
ft1 = time.perf_counter() - t1

t1 = time.perf_counter()
res2 = fibmem(n)
ft2 = time.perf_counter() - t1

t1 = time.perf_counter()
res3 = fibtab(n)
ft3 = time.perf_counter() - t1

print(res1,ft1)
print(res2,ft2)
print(res3,ft3)

55 8.259999958681874e-05
55 5.809999947814504e-05
55 5.059999966761097e-05


In [17]:
# longest common subword 
import numpy as np

def LCW(s1,s2):
    m, n = len(s1), len(s2)
    # construct the grid of m*n zeros 
    # ? notice we have taken m+1 and n+1 to set the base case as 0
    lcw = np.zeros((m+1,n+1))
   
    print(lcw)
    maxw = 0

    # we start filling from reverse order starting from bottom right corner
    for c in range(n-1,-1,-1):
        for r in range(m-1,-1,-1):
            # if the chars are same then fill that position with 1 + lcw[r+1, c+1] 
            # else keep it 0
            if s1[r] == s2[c]:
                lcw[r,c] = 1 + lcw[r+1,c+1]
            else:
                lcw[r,c] = 0
            
            # compare the max 
            if lcw[r,c] > maxw:
                maxw = lcw[r,c]   
    print(lcw)             
    return maxw
s1 = 'bisect'
s2 = 'secret'
print(LCW(s1,s2))

# O(mn)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
3.0


In [19]:
def LCS(s1,s2):
    (m,n) = (len(s1),len(s2))
    lcs = np.zeros((m+1,n+1))
    print(lcs)
    for c in range(n-1,-1,-1):
        for r in range(m-1,-1,-1):
            if s1[r] == s2[c]:
                lcs[r,c] = 1 + lcs[r+1,c+1]
            else:
                lcs[r,c] = max(lcs[r+1,c], lcs[r,c+1])                
    
    print(lcs)
    # max will aways come at 0, 0
    return lcs[0,0] 

s1 = 'secret'
s2 = 'bisect'
print(LCS(s1,s2))
# O(mn)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[4. 4. 4. 3. 2. 1. 0.]
 [3. 3. 3. 3. 2. 1. 0.]
 [2. 2. 2. 2. 2. 1. 0.]
 [2. 2. 2. 2. 1. 1. 0.]
 [2. 2. 2. 2. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
4.0


In [21]:
def ED(u,v):
    m,n = len(u),len(v)
    ed = np.zeros((m+1,n+1))
    print(ed)

    # setting the boundary values 
    for i in range(m-1,-1,-1):
        ed[i,n] = m-i

    for j in range(n-1,-1,-1):
        ed[m,j] = n-j

    for j in range(n-1,-1,-1):
        for i in range(m-1,-1,-1):
            if u[i] == v[j]:
                ed[i,j] = ed[i+1,j+1]
            else:
                ed[i,j] = 1 + min(ed[i+1,j+1], ed[i,j+1], ed[i+1,j])

    print(ed)
    return(ed[0,0])

print(ED('bisect','secret'))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[4. 4. 4. 4. 4. 5. 6.]
 [3. 4. 3. 3. 3. 4. 5.]
 [2. 3. 3. 2. 2. 3. 4.]
 [3. 2. 3. 2. 1. 2. 3.]
 [4. 3. 2. 2. 1. 1. 2.]
 [5. 4. 3. 2. 1. 0. 1.]
 [6. 5. 4. 3. 2. 1. 0.]]
4.0


In [24]:
def MM(dim):
    n = dim.shape[0]
    # cost matrix  
    C = np.zeros((n,n))
    # base case 
    for i in range(n):
        C[i,i] = 0
    # fill diagonally starting from (0, 1), (1, 2), (2, 3), ...
    for diff in range(1,n):
        for i in range(0,n-diff):
            j = i + diff
            C[i,j] = C[i,i] + C[i+1,j] + dim[i][0] * dim[i+1][0] * dim[j][1]
            print(C)
            for k in range(i+1, j+1):
                C[i,j] = min(C[i,j],C[i,k-1] + C[k,j] + dim[i][0] * dim[k][0] * dim[j][1])
            print(C)
    
    return(C[0,n-1])

a = np.array([[2,3],[3,4],[4,5]])
print(MM(a))
# O(n^2) -->fill a table 
# O(n) --> for each entry 
# O(n^3) overall 

3
[[ 0. 24.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0. 24.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0. 24.  0.]
 [ 0.  0. 60.]
 [ 0.  0.  0.]]
[[ 0. 24.  0.]
 [ 0.  0. 60.]
 [ 0.  0.  0.]]
[[ 0. 24. 90.]
 [ 0.  0. 60.]
 [ 0.  0.  0.]]
[[ 0. 24. 64.]
 [ 0.  0. 60.]
 [ 0.  0.  0.]]
64.0


In [23]:
def MM(dim):
    n = len(dim)
    C = []
    for i in range(n):
        L = []
        L=[0]*n
        C.append(L.copy())        
    for diff in range(1,n):
        for i in range(0,n-diff):
            j = i + diff
            KL = []
            for k in range(i, j):
                KL.append(C[i][k] + C[k+1][j] + dim[i][0] * dim[k][1] * dim[j][1])
            C[i][j] = min(KL)
    return(C[0][n-1])
a = [[4,10],[10,3],[3,12],[12,20],[20,7]]
print(MM(a))

1344
