In [12]:
import time 

class TimeError(Exception) : 
    """A custom exception used to report errors in use of Timer Class"""

class Timer : 
    def __init__(self) : 
        self._start_time = None
        self._elapsed_time = None

    def start(self) : 
        """start a new timer"""
        if self._start_time is not None :
            raise TimeError("Timer is running. Use .stop()")
        self._start_time = time.perf_counter()

    def stop(self) : 
        """Save the elapsed time and re-initialize timer"""
        if self._start_time is None : 
            raise TimeError("Timer is not running. User .start()")
        self._elapsed_time = time.perf_counter() - self._start_time
        self._start_time = None

    def elapsed(self) : 
        """Report elapsed time"""
        if self._elapsed_time is None : 
            raise TimeError("Timer is not running. Use .start()")
        retunr (self._elapsed_time)

    def __str__(self) : 
        """print() prints elapsed time"""
        return str(self._elapsed_time)

In [ ]:
# find median (pivot)
# > med --> left 
# < med --> right 
# sort left + sort right 
def quickSort(L, l, r) : 
    if r - l <= 1 : 
        return L 

    pivot, lower, upper = L[l], l+1, l+1 
    
    for i in range(l+1, r) : 
        # extend upper  
        if L[i] > pivot : 
            upper += 1 
        # lowest from upper <> current 
        else : 
            L[i], L[lower] = L[lower], L[i]

            lower, upper = lower+1, upper + 1 

    # pivot <> last of lower  
    # pushing pivot between lower and upper 
    L[l], L[lower-1] = L[lower-1], L[l]
    lower -= 1 

    # sort left and right 
    quickSort(L, l, lower)
    quickSort(L, lower+1, upper)

    return L

# lists updates in place 

# worst case O(n^2)
# avg case O(nlogn) -> can be achieved by randomly choosing the pivot element 
#  often used for built in sorting algo (algo of choice in most cases)

In [ ]:
import sys 

sys.setrecursionlimit(2**31-1)

In [ ]:
qlist = [1, 3, 5, 0, 2, 4, 17, 2, -5, 6, 4, 3]
qnew = quickSort(qlist, 0, 12)

print(qnew,'-->', qlist)

In [ ]:
import random 

random.seed(2021)

inputLists = {}

inputLists['random'] = [random.randrange(100000) for i in range(50000)]
inputLists['asc'] = [i for i in range(50000)]
inputLists['desc'] = [i for i in range(49999, -1, -1)]

t = Timer()
for k in inputLists.keys() : 
    tmplist = inputLists[k][:]
    t.start()
    quickSort(tmplist, 0, len(tmplist))
    t.stop()
    print(k, ' time taken --> ', t) 

# works significantly faster in random case 
# but not in sorted ones in takes way more 

stability --> sorting on one column should not affect the sorting on another column <br> 
--> quick sort is not stable <br> 
--> merge sort is stable <br> 
merge sort is used for external sorting <br> 

heap sort -> O(nlogn)<br> 

we can use hybrid sorting combining mutiple sorting algos <br> 

### List and Array 

**List :**
* flexible length 
* easy to modify structure 
* values are scattered in memory 
(linkedList)
* inserting or deleting is easier

**Array** 
* Fixed size 
* allocate a contiguous block of memory 
* supports random access, accessing any element takes same amount of time  (as size is fixed and type is fixed so you exactly know how much positions to skip for the element)
* inserting or deleting is O(n) worst case
accessing is faster in array 

**Operations** 
* Swap -> array (constant)  list(O(n))
* delete, inset -> array (O(N))  list(constant)

if you insert at right place in a sorted list using binary search then finding middle is easier in array but inserting is easier list 

In [11]:
class Node : 
    def __init__(self, val = None) : 
        self.value = val 
        self.next = None 

    def isEmpty(self) : 
        if self.value == None : 
            return True 
        return False 

    def append(self, val) : 
        if self.isEmpty() : 
            self.value = val  

        else : 
            itr = self 

            while itr.next : 
                itr = itr.next  

            itr.next = Node(val)

        return 

    def appendRec(self, val) : 
        if self.isEmpty() : 
            self.value = val 
        
        elif self.next == None : 
            self.next = Node(val)

        else :
            self.next.append(val)

        return 

    def insert(self, val) : 
        if self.isEmpty() : 
            self.value = val 

        else : 
            newNode = Node(val)

            # exchange values 
            self.value, newNode.value = newNode.value, self.value 
            
            # switch links 
            self.next, newNode.next = newNode, self.next 

        return 

    def delete(self, val) : 
        if self.isEmpty() : 
            return 

        else : 
            itr = self
            while itr.next.next : 
                if itr.next.value == val : 
                    itr.next = itr.next.next 
                    break 
                itr = itr.next 

            if itr.next.value == val : 
                itr.next = None 

    def deleteRec(self, val) : 
        if self.isEmpty() : 
            return 

        if self.value == val : 
             self.value = None 
             if self.next != None : 
                self.value = self.next.value 
                self.next = self.next.next 

        else :
            if self.next != None : 
                self.next.delete(val)
                if self.next.value == None :
                    self.next = None 

        return 

l1 = Node()
l1.isEmpty()

l2 = Node(5)
l2.isEmpty()

l1.insert(2)

**List in python** are not linkedList, they are implemented as array.
 
it declairs a large memory for a list. once the memory reach the size then it double the size 

append and pop are constant time, amortised O(1)

insert and delete -> O(n)

In [3]:
zeroList = [0, 0, 0]
zeroMatrix = [zeroList, zeroList, zeroList]
print(zeroMatrix)

zeroMatrix[1][1] = 1 # mutable 
print(zeroMatrix)
# this happens because every element in zeroMatrix points to the same zeroList 
# so we have to initialize matrix first 

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[0, 1, 0], [0, 1, 0], [0, 1, 0]]


In [5]:
import numpy as np 

zeroMatrix = np.zeros(shape = (3, 3))
print(zeroMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
newArr = np.array([[0, 1], [1, 0]])
print(newArr)

[[0 1]
 [1 0]]


In [7]:
row = np.arange(5)
print(row)

[0 1 2 3 4]


In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

D = 3*A + B
C = np.matmul(A, B)
print(C)
print(D)

[[19 22]
 [43 50]]
[[ 8 12]
 [16 20]]


In [13]:
t = Timer()
t.start()
l = []

for i in range(10**7) : 
    l.append(i)

t.stop()
print(t)

1.9823357999994187


In [19]:
t = Timer()
t.start()
l = []

for i in range(10**5) : 
    l.insert(0, i)

t.stop()
print(t) # much slower

t = Timer()
t.start()
l = []

for i in range(20**4) : 
    l.insert(0, i)

t.stop()
print(t) # much much slower

5.50565959999949
12.8025179999986


In [21]:
def naiveSearch(value, arr) : # O(n)
    for val in arr : 
        if val == value : 
            return True 
    return False 


def binarySearch(value, arr) : # logn
    if arr == [] : 
        return False 

    m = len(arr)//2 

    if value == arr[m] : 
        return True 

    if value > arr[m] : 
        return binarySearch(value, arr[m+1:])
    else : 
        return binarySearch(value, arr[:m])



In [28]:
def naiveSearchArr(value, arr, left, right) : # O(n)
    for i in range(left, right) : 
        if arr[i] == value : 
            return True 
    return False 


def binarySearchArr(value, arr, l, r) : # logn
    if r-l <= 0 : 
        return False 

    m = (l+r)//2 

    if value == arr[m] : 
        return True 

    if value > arr[m] : 
        return binarySearchArr(value, arr, m+1, r)
    else : 
        return binarySearchArr(value, arr, l, m)



In [29]:
l = list(range(0, 100000, 2))

t = Timer()
t.start()

for i in range(301, 1300, 2) : 
    v = naiveSearch(i, l)

t.stop()
print('naive --> ', t)

t.start()

for i in range(301, 1300, 2) : 
    v = binarySearch(i, l)

t.stop()
print('binary --> ', t)


naive -->  0.7977671999997256
binary -->  0.1025841999999102


In [30]:
l = np.arange(0, 100000, 2)

t = Timer()
t.start()

for i in range(301, 1300, 2) : 
    v = naiveSearchArr(i, l, 0, np.prod(l.shape))

t.stop()
print('naive --> ', t) # much slower 

t.start()

for i in range(301, 1300, 2) : 
    v = binarySearchArr(i, l, 0, np.prod(l.shape))

t.stop()
print('binary --> ', t) # much faster 

naive -->  7.136818899998616
binary -->  0.018442499998855055


similarly selection sort, merge sort and insertion sort would be slower in array 

indexing works better in list than array 

### Dictionary 

**Hash function** 
  
* h: S -> X maps a set of vakyes S to a small range f int X = {0, 1, 2... n-1}

    names -> roll number 
* typically |X| << |S|, so there will be collisions. different keys might have same value
* a good hash function will minimize collisions 

SHA-256 is an industry standard hashing function whose range is 256bits 

in practice before uploading file some hashing is done, if the hash of new file is already present then file will not be uploaded again just a copy would be made.

```
dict : 
d[k] = v 
k -> h(k) -> j 
store at jth location
```
if the location is already occupied then we have to avoid collisions. there are 2 methods to handle that.

1. open addresing (closed hashing) :
    we create an array with much large space, if we the required place is occupied then we probe a sequence of alt slots in the same array (e.g. +10 +10 / -10 -10) until we find the space.

2. Open hashing : 
    each slot in the array points to a list of values. in simple terms each element in the array is again an array 

Dict keys in python must be immutable, you can't use list as a key to a dict. because if you update the key then the hash will change and the value will be lost.

### Stack
A Stack is a `non-primitive linear data structure`. It is an ordered list in which the addition of a new data item and deletion of an already existing data item can be done from only one end, known as top of the stack.

The last added element will be the first to be removed from the Stack. That is the reason why stack is also called Last In First Out (LIFO) type of data structure.

**Basic operations on Stack**

1. Push
    The process of adding a new element to the top of the Stack is called the Push operation.
2. Pop
    The process of deleting an existing element from the top of the Stack is called the Pop operation. It returns the deleted value.
3. Traverse/Display
    The process of accessing or reading each element from top to bottom in Stack is called the Traverse operation.

**Applications of Stack**
* Reverse the string
* Evaluate Expression
* Undo/Redo Operation
* Backtracking
* Depth First Search(DFS) in Graph

### Queue
The Queue is a `non-primitive linear data structure`. It is an ordered collection of elements in which new elements are added at one end called the Back end, and the existing element is deleted from the other end called the Front end.

A Queue is logically called a First In First Out (FIFO) type of data structure.

**Basic operations on Queue**
1. Enqueue
    The process of adding a new element at the Back end of Queue is called the Enqueue operation.
2. Dequeue
    The process of deleting an existing element from the Front of the Queue is called the Dequeue operation. It returns the deleted value.

3. Traverse/Display
    The process of accessing or reading each element from Front to Back of the Queue is called the Traverse operation.

**Applications of Queue**
* Spooling in printers
* Job Scheduling in OS
* Waiting list application
* Breadth First Search(BFS) in Graph